commitid r

diff --git a/.cloudbees/workflows/my-automation-2.yaml b/.cloudbees/workflows/my-automation-2.yaml
--- a/.cloudbees/workflows/my-automation-2.yaml
+++ b/.cloudbees/workflows/my-automation-2.yaml
@@ -17,13 +17,17 @@ jobs:
         id: fetch_content
         run: |
           apk add --no-cache curl
-          curl -s -o commit-info.md https://raw.githubusercontent.com/cashokannamalai/spring-petclinic-config-server/main/commit-info.md || (echo "Failed to fetch commit-info.md" && exit 1)
+          curl -s -o commit-info.md https://raw.githubusercontent.com/cashokannamalai/spring-petclinic-config-server/main/commit-info.md
+          if [ $? -ne 0 ]; then
+            echo "Failed to fetch commit-info.md"
+            exit 1
+          fi
           if [ ! -s commit-info.md ]; then
             echo "Error: commit-info.md is empty or could not be fetched."
             exit 1
           fi
           content=$(cat commit-info.md)
-          echo "::set-output name=content::$content"
+          echo "content=${content}" >> $GITHUB_ENV
 
       - name: Publish evidence
         uses: cloudbees-io/publish-evidence-item@v1
@@ -32,4 +36,4 @@ jobs:
             - Workflow ID: ${{ cloudbees.run_id }}
             - URL: https://github.com/cashokannamalai/spring-petclinic-config-server/blob/main/commit-info.md
             - File Content: |
-              ${{ steps.fetch_content.outputs.content }}
+              ${{ env.content }}
