test

diff --git a/.cloudbees/workflows/my-automation.yaml b/.cloudbees/workflows/my-automation.yaml
--- a/.cloudbees/workflows/my-automation.yaml
+++ b/.cloudbees/workflows/my-automation.yaml
@@ -38,6 +38,15 @@ jobs:
         sleep 10
         docker ps -a
 
+    - name: Verify Dockerfile Path
+      uses: docker://alpine:latest
+      run: |
+          ls -l /cloudbees/workspace
+          if [ ! -f /cloudbees/workspace/Dockerfile ]; then
+            echo "Dockerfile not found!"
+            exit 1
+          fi
+
     - name: Build Docker Image
       uses: docker://docker:20.10.9
       run: |
