apiversion

diff --git a/.cloudbees/workflows/my-automation-2.yaml b/.cloudbees/workflows/my-automation-2.yaml
--- a/.cloudbees/workflows/my-automation-2.yaml
+++ b/.cloudbees/workflows/my-automation-2.yaml
@@ -16,16 +16,19 @@ jobs:
         shell: sh
         run: |
           apk add --no-cache curl
-          curl -s https://raw.githubusercontent.com/cashokannamalai/spring-petclinic-config-server/main/commit-info.md -o commit-info.md
-          content=$(cat commit-info.md)
-          echo "$content" > content_output.txt
+          curl -s -o commit-info.md https://raw.githubusercontent.com/cashokannamalai/spring-petclinic-config-server/main/commit-info.md || (echo "Failed to fetch commit-info.md" && exit 1)
+          if [ ! -s commit-info.md ]; then
+            echo "Error: commit-info.md is empty or could not be fetched."
+            exit 1
+          fi
+          cat commit-info.md
 
       - name: Set environment variable
         uses: docker://alpine:latest
         shell: sh
         run: |
-          content=$(cat content_output.txt)
-          echo "export CONTENT_OUTPUT=\"$content\"" > .env
+          content=$(cat commit-info.md)
+          echo "CONTENT_OUTPUT=\"$content\"" > .env
 
       - name: Publish evidence
         uses: cloudbees-io/publish-evidence-item@v1
