CBDEMO-122

diff --git a/.cloudbees/workflows/my-automation-2.yaml b/.cloudbees/workflows/my-automation-2.yaml
--- a/.cloudbees/workflows/my-automation-2.yaml
+++ b/.cloudbees/workflows/my-automation-2.yaml
@@ -1,13 +1,22 @@
 apiVersion: automation.cloudbees.io/v1alpha1
 kind: workflow
-name: My automation
+name: build_and_deploy
 on:
-  push:
+  pull_request:
     branches:
       - main
 jobs:
-  Checkout:
+  Build:
+    outputs:
+      unitTestResults: ${{ steps.RunUnitTest.outputs.mvn_test_stdio1 }}
+      commit_id: ${{ steps.commitinfo.outputs.commit_id }}
+      commit_msg: ${{ steps.commitinfo.outputs.commit_msg }}
+      jira_key: ${{ steps.commitinfo.outputs.jira_key }}
     steps:
+      - name: Configure git
+        uses: docker://alpine/git:latest
+        run: |
+          git config --global --add safe.directory /cloudbees/workspace
       - name: Checkout
         uses: cloudbees-io/checkout@v1
       - name: Get Commit Info
@@ -16,34 +25,27 @@ jobs:
         run: |
           COMMIT_ID=$(git rev-parse HEAD)
           COMMIT_MSG=$(git log -1 --pretty=%B)
+          # Extract the JIRA issue key (assuming format like PROJECTKEY-123)
+          JIRA_KEY=$(echo "$COMMIT_MSG" | grep -oE "[A-Z]+-[0-9]+")
+          if [ -z "$JIRA_KEY" ]; then
+            echo "Error: Commit message must include a valid JIRA issue key." >&2
+            exit 1
+          fi
+
           echo "commit_id=${COMMIT_ID}" >> $CLOUDBEES_OUTPUTS/commit_id
           echo "commit_msg=${COMMIT_MSG}" >> $CLOUDBEES_OUTPUTS/commit_msg
-    outputs:
-      commit_id: ${{ steps.commitinfo.outputs.commit_id }}
-      commit_msg: ${{ steps.commitinfo.outputs.commit_msg }}
-  Build:
-    needs: Checkout
-    outputs:
-      unitTestResults: ${{ steps.RunUnitTest.outputs.mvn_test_stdio1 }}
-    steps:
-      - name: Configure git
-        uses: docker://alpine/git:latest
-        run: |
-          git config --global --add safe.directory /cloudbees/workspace
-      - name: Checkout
-        uses: cloudbees-io/checkout@v1
-      - name: Build
-        uses: docker://maven:3-eclipse-temurin-17
-        run: |
-          mvn clean install
+          echo "jira_key=${JIRA_KEY}" >> $CLOUDBEES_OUTPUTS/jira_key
+      - uses: docker://maven:3-eclipse-temurin-17
+        name: Build
+        kind: build
+        run: mvn clean package
+        shell: sh
       - name: RunUnitTest
         id: RunUnitTest
         uses: docker://maven:3-eclipse-temurin-17
-        run: >
+        run: |
           mvn test > "$CLOUDBEES_OUTPUTS/mvn_test_stdio"
-
-          cat "$CLOUDBEES_OUTPUTS/mvn_test_stdio" | grep "Tests run:" | tail -1
-          > "$CLOUDBEES_OUTPUTS/mvn_test_stdio1"
+          cat "$CLOUDBEES_OUTPUTS/mvn_test_stdio" | grep "Tests run:" | tail -1 > "$CLOUDBEES_OUTPUTS/mvn_test_stdio1"
       - name: Configure container registry credentials
         id: dockerconfig
         uses: cloudbees-io/configure-oci-credentials@v1
@@ -56,8 +58,17 @@ jobs:
         with:
           dockerfile: Dockerfile
           context: .
-          destination: ${{ secrets.STAGING_DOCKER_REGISTRY }}/${{
-            secrets.STAGING_DOCKER_USERNAME }}/configserver:3.2.4
+          destination: ${{ secrets.STAGING_DOCKER_REGISTRY }}/${{ secrets.STAGING_DOCKER_USERNAME }}/configserver:3.2.4
+      - name: Publish evidence
+        uses: cloudbees-io/publish-evidence-item@v1
+        with:
+          content: |
+            ## Commit Information
+            - **Commit ID:** "${{ steps.commitinfo.outputs.commit_id }}"
+            - **Commit Message:** "${{ steps.commitinfo.outputs.commit_msg }}"
+            ## Unit Test Results
+            - **Unit Test Results:** "${{ steps.RunUnitTest.outputs.mvn_test_stdio1 }}"
+            - **JIRA Issue Key:** "${{ steps.commitinfo.outputs.jira_key }}"
   StaticAnalysis:
     outputs:
       BLOCKER_COUNT: ${{ steps.FetchSonarQubeIssues.outputs.BLOCKER_COUNT }}
@@ -65,64 +76,58 @@ jobs:
       MAJOR_COUNT: ${{ steps.FetchSonarQubeIssues.outputs.MAJOR_COUNT }}
       MINOR_COUNT: ${{ steps.FetchSonarQubeIssues.outputs.MINOR_COUNT }}
     steps:
-      - uses: cloudbees-io/sonarqube-sast-scan-code@v1
-        name: Scan
-        kind: scan
+      - name: Checkout
+        uses: cloudbees-io/checkout@v1
+      - name: Scan with GitHub Advanced Security
+        uses: cloudbees-io/github-security-sast-scan-code@v1
         with:
-          server-url: https://sonarqube.cb-demos.io
-          username: ${{ secrets.username }}
-          password: ${{ secrets.password }}
-          language: Java
-      - uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
-        name: Scan with Java
-        kind: scan
-        with:
-          language: JAVA
-      - uses: cloudbees-io/findsecbugs-sast-scan-code@v1
-        name: Scan with Find Security Bugs
-        kind: scan
-        with:
+          token: ${{ secrets.GITHUB_SECRET }}
           language: LANGUAGE_JAVA
-      - uses: sbatchelder-cba/sonarqube-cba@v0.0.3
-        name: Scan GP
+      - name: Scan with SonarQube bundled
+        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v1
         with:
-          project-key: config-server
-          token: ${{ secrets.token }}
+          sonar-exclusion: src/main/java
+          cover-file-name: ./pom.xml
+          language: LANGUAGE_JAVA
+      - uses: cloudbees-io/publish-test-results@v1
+        name: Publish test results
+        kind: test
+        with:
+          test-type: JUnit
+          folder-name: /cloudbees/workspace/target/surefire-reports/*.xml
       - name: Fetch SonarQube Issues
         id: FetchSonarQubeIssues
         uses: docker://alpine/git:latest
-        run: >
+        run: |
           apk add --no-cache curl jq
-
           curl -u ${{ secrets.username }}:${{ secrets.password }} \
-
-          "https://sonarqube.cb-demos.io/api/issues/search?componentKeys=config-server&severities=BLOCKER,CRITICAL,MAJOR"
-          \
-
+          "https://sonarqube.cb-demos.io/api/issues/search?componentKeys=spring-petclinic-config-server&severities=BLOCKER,CRITICAL,MAJOR" \
           -o sonar-issues.json
+          BLOCKER_COUNT=$(jq '[.issues[] | select(.severity=="BLOCKER")] | length' sonar-issues.json)
+          CRITICAL_COUNT=$(jq '[.issues[] | select(.severity=="CRITICAL")] | length' sonar-issues.json)
+          MAJOR_COUNT=$(jq '[.issues[] | select(.severity=="MAJOR")] | length' sonar-issues.json)
+          MINOR_COUNT=$(jq '[.issues[] | select(.severity=="MINOR")] | length' sonar-issues.json)
 
-          BLOCKER_COUNT=$(jq '[.issues[] | select(.severity=="BLOCKER")] |
-          length' sonar-issues.json)
-
-          CRITICAL_COUNT=$(jq '[.issues[] | select(.severity=="CRITICAL")] |
-          length' sonar-issues.json)
-
-          MAJOR_COUNT=$(jq '[.issues[] | select(.severity=="MAJOR")] | length'
-          sonar-issues.json)
-
-          MINOR_COUNT=$(jq '[.issues[] | select(.severity=="MINOR")] | length'
-          sonar-issues.json)
-
-
-          echo "BLOCKER_COUNT=${BLOCKER_COUNT}" >>
-          $CLOUDBEES_OUTPUTS/BLOCKER_COUNT
-
-          echo "CRITICAL_COUNT=${CRITICAL_COUNT}" >>
-          $CLOUDBEES_OUTPUTS/CRITICAL_COUNT
-
+          echo "BLOCKER_COUNT=${BLOCKER_COUNT}" >> $CLOUDBEES_OUTPUTS/BLOCKER_COUNT
+          echo "CRITICAL_COUNT=${CRITICAL_COUNT}" >> $CLOUDBEES_OUTPUTS/CRITICAL_COUNT
           echo "MAJOR_COUNT=${MAJOR_COUNT}" >> $CLOUDBEES_OUTPUTS/MAJOR_COUNT
-
           echo "MINOR_COUNT=${MINOR_COUNT}" >> $CLOUDBEES_OUTPUTS/MINOR_COUNT
+      - name: Publish evidence
+        uses: cloudbees-io/publish-evidence-item@v1
+        with:
+          content: |
+            ## SonarQube Analysis Results
+
+            | Severity And Issue Count |
+            |------------------------|
+
+            |  ${{ steps.FetchSonarQubeIssues.outputs.BLOCKER_COUNT }} |
+
+            | ${{ steps.FetchSonarQubeIssues.outputs.CRITICAL_COUNT }} |
+
+            | ${{ steps.FetchSonarQubeIssues.outputs.MAJOR_COUNT }} |
+
+            |  ${{ steps.FetchSonarQubeIssues.outputs.MINOR_COUNT }} |
   ArtifactPublish:
     needs: Build
     steps:
@@ -136,7 +141,7 @@ jobs:
         env:
           NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
           NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
-        run: >
+        run: |
           mvn deploy \
             -DaltDeploymentRepository=nexus::default::https://${NEXUS_USERNAME}:${NEXUS_PASSWORD}@nexus.cb-demos.io/repository/Petclinic/
   Approval:
@@ -159,7 +164,9 @@ jobs:
           mvn test
   Deploy:
     needs: SmokeTest
-    kind: deploy
+    environment: production
+    outputs:
+      ingress_ip: ${{ steps.getIngressIP.outputs.ingress_ip }}
     steps:
       - name: Checkout
         uses: cloudbees-io/checkout@v1
@@ -167,48 +174,21 @@ jobs:
         name: Set kubeconfig
         with:
           secname: ${{ secrets.kubeconfig }}
-      - uses: docker://bitnami/kubectl:latest
-        name: Deploy image
-        shell: sh
-        run: |
-          kubectl apply -f /cloudbees/workspace/deployment-service.yaml
-  Evidence:
-    needs:
-      - Deploy
-      - Build
-      - Checkout
-      - StaticAnalysis
-    steps:
-      - uses: cloudbees-io/publish-evidence-item@v1
-        name: Publish evidence
+      - uses: cloudbees-io/kustomize-deploy@v1
+        name: deploy
+        kind: deploy
         with:
-          content: >
-            - Workflow ID: ${{ cloudbees.run_id }}
-
-            - URL: ${{ cloudbees.api.url }}
-
-             ## Commit Information
-            - **Commit ID:** "${{ needs.Checkout.outputs.commit_id }}"
-
-            - **Commit Message:** "${{ needs.Checkout.outputs.commit_msg }}"
-
-            - **Unit Test Results:** "${{ needs.Build.outputs.unitTestResults
-            }}"
-
-
-            ## SonarQube Analysis Results
-
-
-            | Severity And Issue Count |
-
-            |------------------------|
-
-            |  ${{ needs.StaticAnalysis.outputs.BLOCKER_COUNT }} |
-
-            |  ${{ needs.StaticAnalysis.outputs.CRITICAL_COUNT }} |
-
-            |  ${{ needs.StaticAnalysis.outputs.MAJOR_COUNT }} |
-
-            |  ${{ needs.StaticAnalysis.outputs.MINOR_COUNT }} |
- 
-
+          kustomization-base-dir: ${{ cloudbees.workspace }}/base
+      - name: Get Ingress IP
+        id: getIngressIP
+        uses: docker://bitnami/kubectl:latest
+        run: |
+          INGRESS_IP=$(kubectl get ingress configserver-ingress -n ashok -o jsonpath="{.status.loadBalancer.ingress[0].ip}")
+          echo "Ingress IP: $INGRESS_IP"
+          echo "ingress_ip=${INGRESS_IP}" >> $CLOUDBEES_OUTPUTS/ingress_ip
+      - name: Publish Ingress IP Evidence
+        uses: cloudbees-io/publish-evidence-item@v1
+        with:
+          content: |
+            ## Deployment Information
+             - **Ingress IP:** "${{ steps.getIngressIP.outputs.ingress_ip }}/config"
